### ISSUE TITLE
Possible MES bug ?

### ISSUE THREAD

**Issue by ssydasheng** [GPflow/GPflowOpt#100]
https://github.com/GPflow/GPflowOpt/blob/cabaac05a67b1a87fdb0b31aedf3bac8119d6b6e/gpflowopt/acquisition/mes.py#L99

In the original paper, `gamma` is computed as `(y* - mu) / sigma`. It seems the code here is reversed.

**Comment by nknudde** [comment]
Hello!

The reason for this is that the paper is written in the sense that they want yo maximize an objective, whiles our framework minimizes a cost function.

**Comment by ssydasheng** [comment]
ah, I see. Thanks
