### ISSUE TITLE
when installing GPflowOpt it is down grading GPflow from 1.2 to  0.4

### ISSUE THREAD

**Issue by pullanagari** [GPflow/GPflowOpt#104]
i have installed latest gpflow version (1.2) using pip
Later when i tried to install gpflowopt using the following code
pip install git+https://github.com/GPflow/GPflowOpt.git

it is down grading GPflow from 1.2 to  0.4

**Comment by javdrher** [comment]
Hi @pullanagari 

This is intended behavior as currently our master branch is not compatible with more recent GPflow versions. We have a PR for this (#91) which nearly fixes all incompatibilities caused by the major changes of 1.0. Unfortunately, there was a severe performance problem. The cause was identified and as far as I know, GPflow now has the required methods to solve the problem. Unfortunately we have been lacking time to finish these changes.

**Comment by pullanagari** [comment]
Hi, I want use the gpflow for multivarite regression, using the following code but noticed with error.


Matrix size-incompatible: In[0]: [100,30], In[1]: [1,1]
	 [[Node: GPR-4c62c2a4-279/likelihood_1/MatMul_1 = MatMul[T=DT_DOUBLE, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](GPR-4c62c2a4-279/X/dataholder/read, Linear-943701e5-256/A/unconstrained/read)]]

import gpflow
import numpy as np

X = np.random.rand(100, 30)
Y = np.sin(12 * X[:,1]).reshape(-1, 1)


k = gpflow.kernels.Matern52(30, lengthscales=2)
meanf = gpflow.mean_functions.Linear(1,0)
m = gpflow.models.GPR(X,Y, k, meanf)
m.likelihood.variance = `0.01`
m.compile()
gpflow.train.ScipyOptimizer().minimize(m, maxiter=20)

**Comment by icouckuy** [comment]
@pullanagari that snipped only uses gpflow and not gpflowopt. Are you sure you have gpflow 1.2 installed? Maybe you are still using the downgraded gpflow 0.4 version which was pulled in by gpflowopt master. Otherwise you better post this better as a gpflow issue.

**Comment by pullanagari** [comment]
yes, i have installed gpflow 1.2 version.

I have used above example but it showing the following error
InvalidArgumentError (see above for traceback): Matrix size-incompatible: In[0]: [100,30], In[1]: [1,1]
	 [[Node: GPR-1916d78d-24/likelihood_1/MatMul_1 = MatMul[T=DT_DOUBLE, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](GPR-1916d78d-24/X/dataholder/read, Linear-3942bedb-17/A/unconstrained/read)]]

**Comment by icouckuy** [comment]
@pullanagari as far as I can see this is a pure GPFlow issue. This is the GPFlowOpt project which is different.

GPFlow issues should be posted at https://github.com/GPflow/GPflow/issues
