### ISSUE TITLE
Advantages of using Tensorflow?

### ISSUE THREAD

**Issue by Amin-Tgz** [GPflow/GPflowOpt#115]
Hi,
whats the advantages of using tf in your code?
if you replace tf with numpy the performance will be changed? (you use only .shape and .matmul function of tf which numpy has the same functions)

**Comment by icouckuy** [comment]
Hi,

There will not be much of a performance difference with numpy at the moment. The most important advantages of using tf is that we get the derivatives of the acquisition functions for free (important for optimization) which makes implementation easier.

Of course gpflow also uses tf, and by staying inside tf for as long as possible we get all the advantages of tf (parallelization, gpu execution, graph optimization, access to tf's optimizers, etc.), but I doubt it will make much of a difference for the standard BO algorithms.

**Comment by Amin-Tgz** [comment]
And also a good keyword for the article 😄
