### ISSUE TITLE
Struggle to proper install gpflowopt

### ISSUE THREAD

**Issue by Stephocke** [GPflow/GPflowOpt#127]
Hi,

your package looks quite interesting. Unfortunately, I cannot install it properly. It requires an old version of gpflow==0.5.0. I was able to install gpflow==0.5.0 from github, however, it seems to be incompatible with tensorflow>=2.0.

I read the issue:
https://github.com/GPflow/GPflowOpt/issues/112 

And following the steps of the last suggestion. However, I cannot pass point 5. I started to adjust some code in the gpflow source files. Eventually, I got the error 'TypeError: Variable is unhashable. Instead, use tensor.ref() as the key.'. This looks like a tensorflow issue. To resolve it, a version below 2.0 is required. 

I tried python 3.6.6, python 3.7 on Windows, and python 3.8 on Ubuntu and got similar errors.
Is there any way, to set up a proper environment? Is the package still maintained?

Kinds regards

**Comment by icouckuy** [comment]
GPFlowOpt is not supported anymore, we have moved to develop Trieste based on the latest GPFlow and Tensorflow versions.
https://github.com/secondmind-labs/trieste
