### ISSUE TITLE
Source organization

### ISSUE THREAD

**Issue by javdrher** [GPflow/GPflowOpt#34]
Right now, the acquisition file is growing in size. Additionally, it is becoming a mix between implementations of algorithms and some elements which aggregate, as well as the baseclass (Acquisition). 

Although the aim is not supporting a full library of acquisition functions, some additions are planned (mostly multi-objective). This means at some point we'll have to split the file. I was thinking of creating an acquisition subpackage, include a base.py, a common.py (with EI, PoI, LCB, PoF), a hvpoi.py, pes.py etc. Then in __init__.py those are loaded, recovering the paths we have now. However I'd like to hear some thoughts on this.

**Comment by icouckuy** [comment]
Seems like a good idea. Will look into it

**Comment by icouckuy** [comment]
Put the common ones in acquisition.py instead of common.py
