### ISSUE TITLE
Package rename

### ISSUE THREAD

**Issue by javdrher** [GPflow/GPflowOpt#50]
FYI: currently, a discussion is ongoing to rename the package GPflow to gpflow: GPflow/GPflow#452 (only in code, the project name remains what it is). If the discussion results in a decision to rename, GPflowOpt will follow.

**Comment by icouckuy** [comment]
Small update: GPflow will be renaming its package to gpflow *29th August*. Hence, we will be switching our package name to gpflowopt too.

However, as we haven't released yet the timing doesn't really matter (for adapting to gpflow's new package name we can even wait until it is actually released).

**Comment by icouckuy** [comment]
Shall I already make branch for this? As far as I can see we should:
- rename the GPflowOpt directory to gpflowopt
- adjust the notebooks
- update setup.py
- update GPflow to point to master in setup.py if it is not tagged immediately?
Anything else?

**Comment by javdrher** [comment]
Go ahead. Do not touch the GPflow dependency link yet, for now we'll be depending on master.

@alexggmatthews , @jameshensman as there is no PyPI GPflow package yet we take care of the GPflow dependency by using the `--process-dependency-links` pip flag. Right now, this points to master but it has occured GPflowOpt master was suddenly broken because a PR was merged into GPflow. So we'd like to rely on on a specific version of GPflow, this can be accomplished by tagging the releases on GitHub.

**Comment by javdrher** [comment]
Thanks for the tags, the rename was successfully completed.
