### ISSUE TITLE
Citation for probability of feasibility

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflowOpt#51]
I notice the probability of feasibility doc string cites 

Parr et al, 2012 : "Infill sampling criteria for surrogate-based optimization with constraint handling"

Should it maybe instead cite:
Schonlau, M., 1997 "Computer experiments and global optimization" .

Parr et al seem to attribute probability of feasibility to this earlier work although perhaps I am missing something.

**Comment by icouckuy** [comment]
@alexggmatthews yes, you are correct. This reference needs updating. We are aware of this for a while but are holding it off for when we are updating the documentation.

One of the discussion points we have is whether we should refer to the first original work introducing the approach, which can be quite old and harder to read. Or refer to a more recent survey (probably in machine learning) which, for instance, summarizes a number of acquisition functions suited for expensive constraints.
