### ISSUE TITLE
Remove default params

### ISSUE THREAD

**Issue by javdrher** [GPflow/GPflowOpt#58]
This early addition for stability comes from the optdemo. Meanwhile many things were improved: do we still need this? it creates errors when after a recompile the free state changes. if removed we retain the previous optimum + random restarts which seems reasonable.

**Comment by icouckuy** [comment]
I'm assuming the hyp callback will allow resetting the hyps in a controlled manner (and allows a single restart which makes sense)? Is this still for 0.1?

Do we provide a callback for the standard GPR model?

**Comment by javdrher** [comment]
I was thinking the standard callback to be the current behavior (start from the previous optimum).
