### ISSUE TITLE
Close TF sessions properly in tests

### ISSUE THREAD

**Issue by javdrher** [GPflow/GPflowOpt#70]
Following the discussion in GPflow/GPflow#472, this also affects our tests. Garbage collecting a tf.session() in python doesn't release its resources. We should fix this, after GPflow/GPflow#471 is merged.

**Comment by awav** [comment]
It is already fixed in #471, because it was a blocker for that task (tests didn't pass before the fix)

**Comment by awav** [comment]
You are welcome to review #471 ;)
