### ISSUE TITLE
Add printing flag to bayesianoptimizer.optimize

### ISSUE THREAD

**Issue by javdrher** [GPflow/GPflowOpt#82]
Add some feedback in optimize, e.g. print each iteration & current best.

**Comment by icouckuy** [comment]
We still want this or do we want to keep the output as lean as possible? As it would be very tempting to add an additional callback in  BayesianOptimizer so the user can do more than printing when needed (make checkpoints, plots, etc.). Alternatively, a user could also call optimize for just one iteration then he has much more fine-grained control over the optimization loop.

**Comment by dgilford** [comment]
I would personally really like some sort of "verbose" option in the optimizer. Without it, it is hard to understand sometimes how the MLL and hyperparameters are evolving.

**Comment by icouckuy** [comment]
@dgilford I agree, as BOptimizer is high-level it can provide some feedback.

At each sampling iteration the MLL of the current model + fmin can be printed:

iter #2, MLL: 1,23e2, fmin: ..., ...
iter #3, MLL: 1,23e1, fmin, ...

If you feel like it you can make a pull request that implements a simple printing statement. I'd be happy to accept it.

**Comment by icouckuy** [comment]
I'm working on adding a print statement. I'm just fighting python formatting and numpy arrays atm. Afterwards I'll male a PR
