### ISSUE TITLE
GPflow 1.0

### ISSUE THREAD

**Issue by javdrher** [GPflow/GPflowOpt#86]
Tomorrow, GPflow 1.0 RC is scheduled for merging into master (see GPflow/GPflow#539). This new version offers a wide range of new features and possibilities for integration at the expensive of a number of severe changes. Over the past weeks I regularly tried the RC branch with GPflowOpt to check all changes we would require, unfortunately this will be quite some work to get it all done properly. Especially the `Acquisition` class requires some serious changes.

For the near future we will depend on 0.4, but I'd like to move to 1.0. It offers the possibility to get rid of some hacks like the ParentHook. However, we will have to drop python 2.7 support. I personally don't see this as a big issue, so I wouldn't mind.

**Comment by icouckuy** [comment]
I'm all for dropping those hacks. When GPflow is on pypi, which is the aim for 1.0 I believe, we can also simplify the setup.py.

If GPflow drops python 2.7 support, GPflowOpt might as well of course. I did encounter some cases where I wanted to use GPflowOpt but I needed a python 2.7 env for some utility library that linked to a simulator (mostly for older libraries or commercial software). I can imagine this is a rare situation and only becomes more rare in the near future.

**Comment by javdrher** [comment]
Work started, see PR for details
