### ISSUE TITLE
TypeError: object() takes no parameters when import gpflowopt

### ISSUE THREAD

**Issue by rm4216** [GPflow/GPflowOpt#93]
Hello everyone,

I have just installed the latest version of gpflowopt (0.1.0) and I'm running a small example:
`import numpy as np
import gpflow
import gpflowopt`
when importing gpflowopt though I receive the following error:

  File "/home/rm4216/GPflowOpt/gpflowopt/__init__.py", line 15, in <module>
    from . import acquisition
  File "/home/rm4216/GPflowOpt/gpflowopt/acquisition/__init__.py", line 16, in <module>
    from .acquisition import Acquisition, AcquisitionAggregation, AcquisitionProduct, AcquisitionSum, MCMCAcquistion
  File "/home/rm4216/GPflowOpt/gpflowopt/acquisition/acquisition.py", line 15, in <module>
    from ..scaling import DataScaler
  File "/home/rm4216/GPflowOpt/gpflowopt/scaling.py", line 19, in <module>
    from .transforms import LinearTransform, DataTransform
  File "/home/rm4216/GPflowOpt/gpflowopt/transforms.py", line 25, in <module>
    class DataTransform(Parameterized):
  File "/home/rm4216/GPflowOpt/gpflowopt/transforms.py", line 32, in DataTransform
    @AutoFlow((float_type, [None, None]))
TypeError: object() takes no parameters

I've also incurred in the same error when building the documentation from the terminal, that is running the following command:
`python setup.py build_sphinx`

I installed gpflowopt within an anaconda environment, with Python 3.5. Tensorflow version 1.4.0, GPflow version 1.1.0, on Ubuntu 16.04.
Have I missed something in the install process?

Thank you.

**Comment by javdrher** [comment]
Hi @rm4216 , thank you for looking at GPflowOpt

unfortunately, GPflowOpt is not compatible yet with GPflow > 1.0.0, latest version we support is 0.4.0, compatibility is a work in progress (see #91 for progress). I'm hoping to finish it around the end of the year.

Kind regards,
Joachim van der Herten

**Comment by rm4216** [comment]
Thank you for the information!

Best regards,
Riccardo
