### ISSUE TITLE
Is GPflowOpt compatible anymore with GPflow functions?

### ISSUE THREAD

**Issue by grahamski2323** [GPflow/GPflowOpt#97]
I just downloaded GPflowOpt, yet nothing can run due to slight changes made in GPflow. For example, you have now made a 'core' subfolder and seemed to changed the AutoFlow function. I have tried to apply come changes on my own (it is not hard to change 'from gpflow.param import DataHolder, Autoflow' to two separate imports in their correct folders, params and core), but note @Autoflow calls now need to be @gpflow.autoflow. I spent several hours changing this for pretty much every function/class.

Yet now it seems certain classes are also significantly changed. 'Parameterized' no longer has the attribute 'highest_parent', something needed for SciPyOptimizer.

At this point, not a single thing can be called from GPflowOpt without error.

Sorry if my explanation is not technical - I am not a trained programmer, rather, a Ph.D. student in applied mathematics.

**Comment by grahamski2323** [comment]
Realized new version of GPflow is not backwards-compatible. Sorry

**Comment by javdrher** [comment]
Hi @grahamski2323 we are working on compatibility (#91) but we suffer from a serious performance issue coming from GPflow which makes it not usable. We are hoping to resolve this.

**Comment by namoshizun** [comment]
Hi @javdrher . I'm currently building an experiment for performing non-myopic Bayesian Optimisation based on Monte-Carlo Tree Search algorithm, in which there will be plenty of GP updates during the Monte-Carlo simulation (~50 small GP updates per second). Do you think GPflow is an appropriate framework for such task?

**Comment by Paarisaa** [comment]
Hi, I have just successfully installed gpflowopt, but gpflow had some issues after this installation such as gpflow has no attribute named models! I reinstalled the gpflow, but now there are issues with gpflowopt! The error is "No module named 'gpflow.param"!
Would you please let me know what should I do to solve the problem?
Which version of gpflow is compatible with gpflowopt?

**Comment by FanwangM** [comment]
I have the same problem. Is `GPFlowOpt` is going to support the latest version of `GPFlow`? Thanks!
